CREATE USER IF NOT EXISTS 'teste'@'%' IDENTIFIED BY 'teste';

CREATE DATABASE IF NOT EXISTS teste;

ALTER DATABASE teste
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON teste.* TO 'teste'@'%' IDENTIFIED BY 'teste';